---

osm_packages:
  - - ruby2.3
    - libruby2.3
    - ruby2.3-dev
    - libmagickwand-dev
    - libxml2-dev
    - libxslt1-dev
    - nodejs
    - apache2
    - apache2-dev
    - build-essential
    - git-core
    - postgresql
    - postgresql-contrib
    - libpq-dev
    - postgresql-server-dev-all
    - libsasl2-dev
    - imagemagick
